[custom.all.pretty-show]
type   = "local"
path   = "."
ipkg   = "pretty-show.ipkg"
test   = "test/test.ipkg"

[custom.all.pretty-show-test]
type   = "local"
path   = "test"
ipkg   = "test.ipkg"

[custom.all.elab-util]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "latest:main"
ipkg   = "elab-util.ipkg"
