[custom.all.pretty-show]
type   = "local"
path   = "."
ipkg   = "pretty-show.ipkg"
test   = "test/test.ipkg"

[custom.all.pretty-show-test]
type   = "local"
path   = "test"
ipkg   = "test.ipkg"

[custom.all.elab-util]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "latest:main"
ipkg   = "elab-util.ipkg"

[custom.all.elab-pretty]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "latest:main"
ipkg   = "elab-pretty.ipkg"

[custom.all.parser]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "latest:unify_errors"
ipkg   = "parser.ipkg"

[custom.all.parser-show]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "latest:unify_errors"
ipkg   = "show/parser-show.ipkg"
